## =============================================================
##
## This base image has jupyterhub installed and runs as the
## default hub user "jovyan" so it is the bare
## minimum to be compatible with binder and other jupyterhub
## cloud services - compare this to the juypyterhub/singleuser image
##
## =============================================================

FROM underworldcode/petsc4py:3.11.2-jupyterhub

USER root

## This has probably already been done. Use || true to
## ignore errors related to that fact

RUN addgroup jovyan  || true
RUN usermod -a -G jovyan jovyan || true

## =============================================================
## In jupyterhub environments we do not want to have anything in
## /home/jovyan at build time that we might want at run time as
## this is usually clobbered. We install various extensions
## to jupyter and have their configuration be in /user_data by
## default. This directory is also available for other user content
## =============================================================

RUN mkdir -p /user_data
RUN mkdir -p /user_data/content
RUN chmod +rx /user_data && chown -R jovyan:jovyan /user_data

WORKDIR  /user_data/

ENV JUPYTERLAB_DIR=/user_data/jupyterlab

RUN pip install jupyterlab --upgrade
RUN pip install jupyterlab-git
RUN pip install jupyter-server-proxy --upgrade
RUN pip install jupyterlab_github --upgrade
RUN jupyter labextension install @jupyterlab/hub-extension
RUN jupyter labextension install @jupyterlab/google-drive
RUN jupyter labextension install @jupyterlab/git
RUN jupyter serverextension enable --py jupyterlab_git  --sys-prefix
RUN jupyter labextension install jupyterlab-server-proxy
RUN jupyter labextension install @mflevine/jupyterlab_html
RUN jupyter labextension install @jupyterlab/github
RUN jupyter serverextension enable --sys-prefix jupyterlab_github
RUN jupyter serverextension enable --sys-prefix jupyter_server_proxy
RUN jupyter lab build

# expose notebook port and any other servers
EXPOSE 8888

# note we use xvfb which to mimic the X display for lavavu and
# other services that expect some X environment to be available

# script for xvfb-run.  all docker commands will effectively run under this via the entrypoint
RUN printf "#\041/bin/sh \n rm -f /tmp/.X99-lock && xvfb-run -s '-screen 0 1600x1200x16' \$@" > /usr/local/bin/xvfbrun.sh && \
                    chmod +x /usr/local/bin/xvfbrun.sh


ENTRYPOINT ["/usr/local/bin/xvfbrun.sh"]
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=''", "--default_url=/lab/tree/PYE_2019/Notebooks/0-StartHere.ipynb" ]

## =============================================================
## DEMO content follows ...
## Some sample functionality: stripy and lavavu
## =============================================================

RUN pip install lavavu --upgrade
RUN pip install imageio
RUN pip install cloudstor
RUN pip install git+https://github.com/underworldcode/stripy
RUN pip install litho1pt0


## =============================================================
# This ensures that any notebooks (etc) we add into the user_data space
# will appear in the default location if we run the container stand alone.
# In the normal way this will be nuked by the hub mount of /home/jovyan

USER jovyan
RUN ln -s /user_data/content /home/jovyan
WORKDIR  /home/jovyan/
